; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=sandbox-vectorizer -sbvec-passes="seed-collection(enable-diff-types)<load-store-vec>" -sbvec-collect-seeds=stores,loads -sbvec-vec-reg-bits=1024 %s -S | FileCheck %s

; Top-level load-seeded vectorization: unlike a load that only feeds a store
; (see load_store_vec.ll), a load bundle discovered as a seed can have
; arbitrary uses, so each original load must be replaced with an extract from
; the new vector load rather than simply discarded.
define i8 @vectorize_loads_general_uses(ptr %ptr) {
; CHECK-LABEL: @vectorize_loads_general_uses(
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr i8, ptr [[PTR:%.*]], i32 0
; CHECK-NEXT:    [[VECIINITL:%.*]] = load <2 x i8>, ptr [[PTR0]], align 1, !sandboxvec [[META0:![0-9]+]]
; CHECK-NEXT:    [[UNPACK:%.*]] = extractelement <2 x i8> [[VECIINITL]], i32 0, !sandboxvec [[META0]]
; CHECK-NEXT:    [[UNPACK1:%.*]] = extractelement <2 x i8> [[VECIINITL]], i32 1, !sandboxvec [[META0]]
; CHECK-NEXT:    [[SUM:%.*]] = add i8 [[UNPACK]], [[UNPACK1]]
; CHECK-NEXT:    ret i8 [[SUM]]
;
  %ptr0 = getelementptr i8, ptr %ptr, i32 0
  %ptr1 = getelementptr i8, ptr %ptr, i32 1
  %ld0 = load i8, ptr %ptr0
  %ld1 = load i8, ptr %ptr1
  %sum = add i8 %ld0, %ld1
  ret i8 %sum
}

; Regression test: -sbvec-collect-seeds=stores,loads used to assert in
; areConsecutive<StoreInst> because runOnRegion() unconditionally treated the
; seed slice as a store chain. It must vectorize both kinds correctly now.
define i8 @vectorize_loads_and_stores_seeds(ptr %ptr, ptr %dst) {
; CHECK-LABEL: @vectorize_loads_and_stores_seeds(
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr i8, ptr [[PTR:%.*]], i32 0
; CHECK-NEXT:    [[DST0:%.*]] = getelementptr i8, ptr [[DST:%.*]], i32 0
; CHECK-NEXT:    [[VECIINITL:%.*]] = load <2 x i8>, ptr [[PTR0]], align 1, !sandboxvec [[META1:![0-9]+]]
; CHECK-NEXT:    [[UNPACK:%.*]] = extractelement <2 x i8> [[VECIINITL]], i32 0, !sandboxvec [[META1]]
; CHECK-NEXT:    [[UNPACK1:%.*]] = extractelement <2 x i8> [[VECIINITL]], i32 1, !sandboxvec [[META1]]
; CHECK-NEXT:    [[SUM:%.*]] = add i8 [[UNPACK]], [[UNPACK1]]
; CHECK-NEXT:    store <2 x i8> <i8 0, i8 1>, ptr [[DST0]], align 1, !sandboxvec [[META2:![0-9]+]]
; CHECK-NEXT:    ret i8 [[SUM]]
;
  %ptr0 = getelementptr i8, ptr %ptr, i32 0
  %ptr1 = getelementptr i8, ptr %ptr, i32 1
  %dst0 = getelementptr i8, ptr %dst, i32 0
  %dst1 = getelementptr i8, ptr %dst, i32 1
  %ld0 = load i8, ptr %ptr0
  %ld1 = load i8, ptr %ptr1
  %sum = add i8 %ld0, %ld1
  store i8 0, ptr %dst0
  store i8 1, ptr %dst1
  ret i8 %sum
}

; A mixed-type load chain can't be turned back into per-element extracts (the
; combined vector's element type is narrower than some of the loads), so it
; must be left scalar rather than mis-vectorized.
define i32 @vectorize_loads_mixed_types_not_vectorized(ptr %ptr) {
; CHECK-LABEL: @vectorize_loads_mixed_types_not_vectorized(
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr i8, ptr [[PTR:%.*]], i32 0
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr [[PTR]], i32 4
; CHECK-NEXT:    [[LD0:%.*]] = load i32, ptr [[PTR0]], align 4
; CHECK-NEXT:    [[LD1:%.*]] = load i16, ptr [[PTR1]], align 2
; CHECK-NEXT:    [[EXT:%.*]] = zext i16 [[LD1]] to i32
; CHECK-NEXT:    [[SUM:%.*]] = add i32 [[LD0]], [[EXT]]
; CHECK-NEXT:    ret i32 [[SUM]]
;
  %ptr0 = getelementptr i8, ptr %ptr, i32 0
  %ptr1 = getelementptr i8, ptr %ptr, i32 4
  %ld0 = load i32, ptr %ptr0
  %ld1 = load i16, ptr %ptr1
  %ext = zext i16 %ld1 to i32
  %sum = add i32 %ld0, %ext
  ret i32 %sum
}
