; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=sandbox-vectorizer -sbvec-passes="seed-collection<load-store-vec>" -mtriple=amdgpu9.00--amdhsa %s -S | FileCheck %s

define void @basic(ptr %ptr0) {
; CHECK-LABEL: define void @basic(
; CHECK-SAME: ptr [[PTR0:%.*]]) {
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr inbounds i8, ptr [[PTR0]], i64 4
; CHECK-NEXT:    [[LD0:%.*]] = load float, ptr [[PTR0]], align 4
; CHECK-NEXT:    [[LD1:%.*]] = load float, ptr [[PTR1]], align 4
; CHECK-NEXT:    [[PACK:%.*]] = insertelement <2 x float> poison, float [[LD0]], i32 0, !sandboxvec [[META0:![0-9]+]]
; CHECK-NEXT:    [[PACK1:%.*]] = insertelement <2 x float> [[PACK]], float [[LD1]], i32 1, !sandboxvec [[META0]]
; CHECK-NEXT:    store <2 x float> [[PACK1]], ptr [[PTR0]], align 1, !sandboxvec [[META0]]
; CHECK-NEXT:    ret void
;
  %ptr1 = getelementptr inbounds i8, ptr %ptr0, i64 4

  %ld0 = load float, ptr %ptr0
  %ld1 = load float, ptr %ptr1

  store float %ld0, ptr %ptr0
  store float %ld1, ptr %ptr1
  ret void
}
;.
; CHECK: [[META0]] = distinct !{!"sandboxregion"}
;.
